language: python

python:
  - "3.7.3"

sudo: required

install:
  - pip install flask

script:
  - python test.py

deploy:
  provider: heroku
  api-key: 
    secure: JNMnW5Znf1O0V6tc28Lx7DGf1g2w1tmYrF0kJ4siclGlweEdhQkz5uQGO5biCJEogsXwmo/d3+jXuaE4kOxUk/riAqWjxlXSI6K5pBze2SkNS9LYRON3nGgF/rgDMDrzZVODSXiJHitxvTk3p/YD4KgYgJ52W2KHVZCv9RoN4h3RE0jjkgLwB+wup79TfkfPk9JV5spSPUSrJpCWJGf589pXDGz67JfCA6EbZJg+Dy1uOuS2e+d3n9GwYezUlS1+M+hFWbToYWqiBsmbA0qc1kB2tiF7RwCLb4sM/UIhQ7RFZiffSd4F6jZ1kYHb5G7S8/j1iuGEf45ODdN/I5h8ydZAr4Vvww2K/e5u8N2INcs93S5fu/YP3pWOnE+9l5ZzmUccMAJK2rYPBOYGuiPmjjKS13HE8t2nVyrzIa07lGZQriMc7h19OVEMO+C/4roi8aK8WZ/n785Mow1JVgQpV5W2SqoJdiJfNkg0b8y6Hi37Le+OE+rUCPSo7ElOsfBW9v2M62gh4/aTbqSzOoRBJ6sPw9l1/l+R3zUy3qYsMyHVWK9JAAC7eMTT1A4s8cxXilZkNwnNqg9gHVPU78jYr6HDXtvSV6H1HOuN9dqk0Yyixy5f0eiqeqv3F+jNwSCMPhvJNWyy14zAKae44Ngo9kUXQGWcQuF4HIUPcW8VJrQ=
  app: hwpy
